// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqzRD_WLsIiwYnXSXjtY3CXv99zuYSci4',
    appId: '1:979827807455:web:77ab209010719ff06e456a',
    messagingSenderId: '979827807455',
    projectId: 'chatapp-861f4',
    authDomain: 'chatapp-861f4.firebaseapp.com',
    storageBucket: 'chatapp-861f4.appspot.com',
    measurementId: 'G-BGCR7KQGL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB872Z7xnZCOXYx7llDiPv5g1VjOJUCC0M',
    appId: '1:979827807455:android:cdd35900567885ef6e456a',
    messagingSenderId: '979827807455',
    projectId: 'chatapp-861f4',
    storageBucket: 'chatapp-861f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc47vcKCl0cdLAtoHRqfTKJ0sW77wVcb8',
    appId: '1:979827807455:ios:b8bd9543c8a6278e6e456a',
    messagingSenderId: '979827807455',
    projectId: 'chatapp-861f4',
    storageBucket: 'chatapp-861f4.appspot.com',
    iosClientId: '979827807455-72705kudmr1j90t1ovg159k2p0frimn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc47vcKCl0cdLAtoHRqfTKJ0sW77wVcb8',
    appId: '1:979827807455:ios:7cb3bf22ea10cf8c6e456a',
    messagingSenderId: '979827807455',
    projectId: 'chatapp-861f4',
    storageBucket: 'chatapp-861f4.appspot.com',
    iosClientId: '979827807455-7aaoggf24jbdgtkqmfpguel5sn91emb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
